@php($user = auth()->user())
@php($role = $user->role?->value ?? 'personnel')
<x-app-layout>
    @if($role === 'personnel')
        <section class="pa-screen pa-screen-narrow"><div class="pa-welcome-row"><div><p class="pa-eyebrow">Bonjour,</p><h1>{{ $user->name }}</h1></div><button class="pa-icon-button pa-bell" aria-label="Notifications">♧</button></div><div class="pa-status-card"><span>Statut du jour</span><strong>✓ {{ $attendanceStatus->label() }}</strong><a class="pa-light-button" href="{{ route('attendance.scan') }}"><span>⌗</span>Scanner le QR code</a></div><div class="pa-stat-grid"><div class="pa-stat-card"><strong>{{ $todayPointages }}</strong><span>Pointages aujourd’hui</span></div><div class="pa-stat-card"><strong>2</strong><span>Absences</span></div></div><section class="pa-card pa-profile-summary"><h2>Mon profil</h2><dl><div><dt>Poste</dt><dd>Assistant technique</dd></div><div><dt>Centre</dt><dd>CENADI Douala</dd></div></dl><a class="pa-outline-button" href="{{ route('absences.index') }}">Soumettre un justificatif</a></section></section>
    @elseif($role === 'administrateur')
        <section class="pa-screen"><div class="pa-section-heading"><div><p class="pa-eyebrow">Espace administration</p><h1>Gestion des utilisateurs</h1><p class="pa-muted">Administrateur</p></div><div class="pa-avatar pa-avatar-large">AD</div></div><div class="pa-search-row"><input class="pa-input" placeholder="Rechercher un utilisateur" data-list-search="[data-user-list]" aria-label="Rechercher un utilisateur"><button class="pa-icon-button pa-search-button">⌕</button></div><div class="pa-total-banner"><span>Total des utilisateurs</span><strong>{{ $adminUserCount }}</strong></div><section class="pa-card pa-list-card" data-user-list>@forelse($adminUsers as $managedUser)<div class="pa-user-row" data-search-item><div class="pa-avatar">{{ collect(explode(' ', $managedUser->name))->map(fn($part)=>strtoupper(substr($part,0,1)))->join('') }}</div><div><strong>{{ $managedUser->name }}</strong><span>{{ $managedUser->profile?->position ?? $managedUser->role->value }}</span></div><a class="pa-more-button" href="{{ route('admin.users.edit', $managedUser) }}" aria-label="Modifier {{ $managedUser->name }}">›</a></div>@empty<div class="pa-empty">Aucun utilisateur.</div>@endforelse</section><div class="pa-actions-row"><a class="pa-outline-button" href="{{ route('admin.users.index') }}">Voir tous les utilisateurs</a><a class="pa-primary-button" href="{{ route('admin.users.create') }}">＋ Ajouter un utilisateur</a></div></section>
    @else
        @if($role === 'responsable_personnel')
            <section class="pa-screen pa-screen-narrow">
                <div class="pa-section-heading"><div><p class="pa-eyebrow">Espace RH</p><h1>QR du jour</h1><p class="pa-muted">Créez et gérez le QR de pointage du centre.</p></div><div class="pa-avatar pa-avatar-large">RP</div></div>
                @if(session('daily_qr_message'))<div class="pa-attendance-success" role="status">{{ session('daily_qr_message') }}</div>@endif
                <section class="pa-card pa-qr-management">
                    <div class="pa-qr-state"><span class="pa-qr-dot {{ $dailyQr?->is_active ? 'is-active' : '' }}"></span><span>{{ $dailyQr ? 'QR actif aujourd’hui' : 'Aucun QR actif aujourd’hui' }}</span></div>
                    @if(session('daily_qr_token'))<code class="pa-qr-token">{{ session('daily_qr_token') }}</code><p class="pa-muted">Conservez cette valeur pour générer ou afficher le QR du jour.</p>@elseif($dailyQr)<p class="pa-muted">Un QR est déjà créé aujourd’hui. Régénérez-le si vous devez remplacer le support affiché.</p>@else<p class="pa-muted">Aucun QR n’a encore été créé pour le pointage d’aujourd’hui.</p>@endif
                    @if($site)<form method="POST" action="{{ route('attendance.qr-tokens.store') }}">@csrf<input type="hidden" name="site_id" value="{{ $site->id }}"><button class="pa-primary-button pa-full-button" type="submit">{{ $dailyQr ? 'Vérifier le QR du jour' : 'Créer le QR du jour' }}</button></form>@endif
                    @if($dailyQr)<form method="POST" action="{{ route('attendance.qr-tokens.regenerate') }}" class="pa-qr-action">@csrf<input type="hidden" name="site_id" value="{{ $site->id }}"><button class="pa-outline-button pa-full-button" type="submit">Régénérer le QR</button></form><form method="POST" action="{{ route('attendance.qr-tokens.deactivate', $dailyQr) }}" class="pa-qr-action">@csrf @method('PATCH')<button class="pa-danger-button" type="submit">Désactiver le QR</button></form>@endif
                </section>
            </section>
        @endif
        <section class="pa-screen"><div class="pa-section-heading"><div><p class="pa-eyebrow">Espace RH</p><h1>{{ $role === 'chef_centre' ? 'Suivi du centre' : 'Espace RH' }}</h1><p class="pa-muted">{{ $role === 'chef_centre' ? 'Chef de centre' : 'Responsable personnel' }}</p></div><div class="pa-avatar pa-avatar-large">RP</div></div><div class="pa-search-row"><input class="pa-input" placeholder="Rechercher un personnel présent" aria-label="Rechercher un personnel"><button class="pa-icon-button pa-search-button">⌕</button></div><section class="pa-card pa-list-card"><div class="pa-card-title"><h2>Justificatifs à traiter</h2><a href="{{ route('absences.index') }}">Voir tout</a></div><div class="pa-review-row"><div><strong>Fouda Marie</strong><span>Absence du 12/09</span></div><span class="pa-badge pa-badge-warning">En attente</span></div><div class="pa-review-row"><div><strong>Nguemo Paul</strong><span>Retard du 14/09</span></div><span class="pa-badge pa-badge-success">Approuvé</span></div></section><section class="pa-card pa-report-callout"><div><h2>Rapport mensuel</h2><p>Septembre 2026</p></div><a class="pa-outline-button" href="{{ route('reports.index') }}">⇩ Exporter</a></section></section>
    @endif
</x-app-layout>
