@php($user = auth()->user())
@php($role = $user->role?->value ?? 'personnel')
<x-app-layout>
    @if($role === 'personnel')
        <section class="pa-screen pa-screen-narrow"><div class="pa-welcome-row"><div><p class="pa-eyebrow">Bonjour,</p><h1>{{ $user->name }}</h1></div><button class="pa-icon-button pa-bell" aria-label="Notifications">♧</button></div><div class="pa-status-card"><span>Statut du jour</span><strong>✓ Non pointé</strong><a class="pa-light-button" href="{{ route('attendance.scan') }}"><span>⌗</span>Scanner le QR code</a></div><div class="pa-stat-grid"><div class="pa-stat-card"><strong>18</strong><span>Jours présents ce mois</span></div><div class="pa-stat-card"><strong>2</strong><span>Absences</span></div></div><section class="pa-card pa-profile-summary"><h2>Mon profil</h2><dl><div><dt>Poste</dt><dd>Assistant technique</dd></div><div><dt>Centre</dt><dd>CENADI Douala</dd></div></dl><a class="pa-outline-button" href="{{ route('absences.index') }}">Soumettre un justificatif</a></section></section>
    @elseif($role === 'administrateur')
        <section class="pa-screen"><div class="pa-section-heading"><div><p class="pa-eyebrow">Espace administration</p><h1>Gestion des utilisateurs</h1><p class="pa-muted">Administrateur</p></div><div class="pa-avatar pa-avatar-large">AD</div></div><div class="pa-search-row"><input class="pa-input" placeholder="Rechercher un utilisateur" data-list-search="[data-user-list]" aria-label="Rechercher un utilisateur"><button class="pa-icon-button pa-search-button">⌕</button></div><div class="pa-total-banner"><span>Total des utilisateurs</span><strong>142</strong></div><section class="pa-card pa-list-card" data-user-list><x-user-row initials="FM" name="Fouda Marie" role="Employé"/><x-user-row initials="NP" name="Nguemo Paul" role="Chef de centre"/><x-user-row initials="AJ" name="Ateba Jean" role="Employé"/></section><button class="pa-primary-button pa-full-button" data-toast="Formulaire d’ajout bientôt disponible">＋ Ajouter un utilisateur</button></section>
    @else
        <section class="pa-screen"><div class="pa-section-heading"><div><p class="pa-eyebrow">Espace RH</p><h1>{{ $role === 'chef_centre' ? 'Suivi du centre' : 'Espace RH' }}</h1><p class="pa-muted">{{ $role === 'chef_centre' ? 'Chef de centre' : 'Responsable personnel' }}</p></div><div class="pa-avatar pa-avatar-large">RP</div></div><div class="pa-search-row"><input class="pa-input" placeholder="Rechercher un personnel présent" aria-label="Rechercher un personnel"><button class="pa-icon-button pa-search-button">⌕</button></div><section class="pa-card pa-list-card"><div class="pa-card-title"><h2>Justificatifs à traiter</h2><a href="{{ route('absences.index') }}">Voir tout</a></div><div class="pa-review-row"><div><strong>Fouda Marie</strong><span>Absence du 12/09</span></div><span class="pa-badge pa-badge-warning">En attente</span></div><div class="pa-review-row"><div><strong>Nguemo Paul</strong><span>Retard du 14/09</span></div><span class="pa-badge pa-badge-success">Approuvé</span></div></section><section class="pa-card pa-report-callout"><div><h2>Rapport mensuel</h2><p>Septembre 2026</p></div><a class="pa-outline-button" href="{{ route('reports.index') }}">⇩ Exporter</a></section></section>
    @endif
</x-app-layout>
